### ISSUE TITLE
How does Craig dig up those functions and their usage?

### ISSUE THREAD

**Issue by akakoori** [AnotherBugworm/Borderlands2Patcher#1]
I tried typing `Display GD_Shields.A_Item.Shield_Roid_05_ThresherRaid` and `GetAll GD_Shields.A_Item.Shield_Roid_05_ThresherRaid` in the console, just got nothing.
Where and how did you awesome guys do that?
Thanks.

**Comment by bugworm** [comment]
`obj dump GD_Shields.A_Item.Shield_Roid_05_ThresherRaid`. You can join his discord server and ask him or other guys that made custom patches https://discord.gg/0YjZxbVBS9b3bXUS 
P.S. He is ShadowEvil actually, craig is only youtube channel name

**Comment by akakoori** [comment]
wow, thanks a lot
