### ISSUE TITLE
Problem with "exec Patch.txt"

### ISSUE THREAD

**Issue by Valiens** [AnotherBugworm/Borderlands2Patcher#5]
BorderlandsPatcher works just fine for me, however when I go to the menu and do "**exec Patch.txt**" or "**exec PatchOffline.txt**" it just crashes my game and further more after that crash my **Borderland2.exe** is no longer in the win32 folder. That seems bizarre and I can't find any solution online. If you know what might cause this I would appriciate any help.

**Comment by bugworm** [comment]
If you doesn't have .exe file, how did you manage to launch the game?

**Comment by Valiens** [comment]
I launch it, I open up command line, I type exec Patch.txt, then the game crashes and I then don't have the original .exe. Ofc I backed up so I end up restoring it and then again tried to do just that and had the same result. On my 4th attemt it worked , it didn't crash and patch was applied, but since I didn't change any of the steps above I am not sure it that was the exception or not.

**Comment by bugworm** [comment]
Sounds like antivirus. You can try to disable it and try again, if you want to make sure. Closing issue, but you can comment if you want to share result
