### ISSUE TITLE
Cant find file

### ISSUE THREAD

**Issue by LundbergV2** [AnotherBugworm/Borderlands2Patcher#8]
So it tells me that i need to select the right folder, but it never gave me any option to pick a folder what to do

**Comment by bugworm** [comment]
You can drag&drop your `borderlands2(or presequel).exe` into first button (Patch bl.exe). It wont work for downloading patch tho, you should downlad it manually. I'll check code, maybe it's a bug

**Comment by bugworm** [comment]
It it ask you about borderlands folder, it should open file dialog. See https://github.com/bugworm/BorderlandsPatcher/blob/188d4aa229747c6880003ac979e9b67aa33dcc88/BorderlandsPatcher/Form1.cs#L27-L50
@LundbergV2 if you have questions, please reopen issue
